[build]
  command = "pnpm run build"  # 'npm start' 대신 'npm run build'를 사용하여 빌드된 파일을 배포합니다.
  publish = "dist"          # 'build' 폴더에 최적화된 파일이 생성됩니다.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
